### PR TITLE
fix #143 broken hook data

### LINKED ISSUE #143: Broken hook data
When we set initial coordinates for some object and these coordinates belongs to subscribed region data for _inside_ hook is broken.

Steps to reproduce.
1. In first terminal
```
127.0.0.1:9851> nearby fleet FENCE point 33.5123 -112.2693 600
{"ok":true,"live":true}
```
2. In second terminal
```
127.0.0.1:9851> set fleet truck1 point 33.5123 -112.2693
{"ok":true,"elapsed":"68.993µs"}
```

Then in first terminal:
```
{"command":"set","group":"589af129375e4f2747a798ac","detect":"enter","key":"fleet","time":"2017-02-08T13:21:29.288927204+03:00","id":"truck1","object":{"type":"Point","coordinates":[-112.2693,33.5123]}}
{"command":"set","group":"589af129375e4f2747a798ac","detect":"inside","key":"fleet","time":"2017-02-08T13:21:29.288927204+03:00","command":"set","group":"589af129375e4f2747a798ac","detect":"enter","key":"fleet","time":"2017-02-08T13:21:29.288927204+03:00","id":"truck1","object":{"type":"Point","coordinates":[-112.2693,33.5123]}}
```

Second hook contains duplicated keys from first hook: command, group, detect.

### PR DESCRIPTION
**Pull request by mkabischev**

### CODE REVIEW

File: controller/fence.go [hunk 1]
```diff
@@ -194,10 +194,13 @@ func fenceMatch(hookName string, sw *scanWriter, fence *liveFenceSwitches, metas
 
 	msgs := make([][]byte, 0, 4)
 	if fence.detect == nil || fence.detect[detect] {
-		if len(res) > 0 && res[0] == '{' {
-			res = makemsg(details.command, group, detect, hookName, metas, details.key, details.timestamp, res[1:])
+		if fence.detect == nil || fence.detect[detect] {
```
Comment (regeda) [inline controller/fence.go]: I think 196 and 197 lines are equal

Comment (tidwall) [inline controller/fence.go]: Good catch. I just removed the redundant line and pushed to master.
