### PR TITLE
Prevent certain Lua modules/functions from loading

### LINKED ISSUE #630: Lua Sanitization
**Describe the bug**
Tile38's `EVAL` command does not sanitize Lua code. This allows an attacker to use arbitrary code to potentially access information on the machine and opens a door for lateral movement.

**To Reproduce**
Send arbitrary code using `EVAL` to a Tile38 server, such as:
```
https://tile38.fakedomain.com/eval+return{io.popen("printenv"):read('*a')}+0
```

**Logs**
The above command returns the following JSON:
```
{
  "ok": true,
  "result": [
    "HOSTNAME=tile38host\nSHLVL=1\nHOME=/root\nPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\nPWD=/\n"
  ],
  "elapsed": "1.03398ms"
}
```

**Additional context**
I'm not sure if this is out of scope for Tile38, and should be resolved at the administrator's level, but if so, feel free to close this then.

### PR DESCRIPTION
**Pull request by program--**
This PR resolves #630.

## Changes:
- Modified `lua.NewState()` call to open **only** the following modules:
    * base\*
    * table
    * math
    * string
    * os\*
    > \* Only opens `base.tonumber()`, `base.tostring()`, `os.clock()`, and `os.difftime()`.
- Vendored internal Lua function implementations for the subset functions from `gopher-lua` (required to open the subsets, otherwise entire module is available).
- Added `scripts_VULN_tests` into `tests/scripts_test.go`; tests for function existence.

All tests pass using go version 1.19.3 on Linux.

### CODE REVIEW

File: internal/server/scripts.go [hunk 1]
```diff
@@ -26,6 +26,9 @@ const (
 	maxLuaPoolSize = 1000
 )
 
+// For Lua os.clock() impl
+var startedAt time.Time
```
Comment (tidwall) [inline internal/server/scripts.go:30]: This can be simplified as `var startedAt = time.Now()`, with the `init()` function removed altogether.

File: internal/server/scripts.go [hunk 2]
```diff
@@ -844,3 +874,82 @@ func (s *Server) luaTile38NonAtomic(msg *Message) (resp.Value, error) {
...
+func baseToNumber(L *lua.LState) int {
+	base := L.OptInt(2, 10)
+	noBase := L.Get(2) == lua.LNil
+
+	switch lv := L.CheckAny(1).(type) {
+	case lua.LNumber:
+		L.Push(lv)
+	case lua.LString:
+		str := strings.Trim(string(lv), " \n\t")
+		if strings.Index(str, ".") > -1 {
```
Comment (tidwall) [inline internal/server/scripts.go:916]: Perhaps `if strings.Contains(str, ".")`

File: internal/server/scripts.go [hunk 3]
```diff
@@ -844,3 +874,82 @@ func (s *Server) luaTile38NonAtomic(msg *Message) (resp.Value, error) {
...
+// Lua tostring()
+func baseToString(L *lua.LState) int {
+	v1 := L.CheckAny(1)
+	L.Push(L.ToStringMeta(v1))
+	return 1
+}
+
+// Lua os.clock()
+func osClock(L *lua.LState) int {
+	L.Push(lua.LNumber(float64(time.Now().Sub(startedAt)) / float64(time.Second)))
```
Comment (tidwall) [inline internal/server/scripts.go:947]: May I suggest? `L.Push(lua.LNumber(time.Since(startedAt).Seconds()))`

Comment (program--) [reply internal/server/scripts.go]: added in [02a614b](https://github.com/tidwall/tile38/pull/663/commits/02a614bc6db5102a9cd2d63c92d2349139481b03).

File: internal/server/scripts.go (hunk 2 above)
Comment (program--) [reply internal/server/scripts.go]: added in [02a614b](https://github.com/tidwall/tile38/pull/663/commits/02a614bc6db5102a9cd2d63c92d2349139481b03).

File: internal/server/scripts.go (hunk 1 above)
Comment (program--) [reply internal/server/scripts.go]: added in [02a614b](https://github.com/tidwall/tile38/pull/663/commits/02a614bc6db5102a9cd2d63c92d2349139481b03).

**Comment by program--** [comment]
@tidwall Do you have a preference between using nested functions versus the current function definitions I've added? (i.e. `osClock`, `osDiffTime`, etc.)

I noticed in `lStatePool.New()` that you implement some Lua package module functions, but nest the function definitions within `.New()`.

I could move the definitions directly into `openOsSubset` and `openBaseSubset` so they don't pollute the internal namespace, but I guess that's more of a style choice than anything else.

**Comment by tidwall** [comment]
> I could move the definitions directly into openOsSubset and openBaseSubset so they don't pollute the internal namespace, but I guess that's more of a style choice than anything else.

I'm fine with your approach.

**Comment by tidwall** [comment]
LGTM. Thanks 👍
